stages:
  - build

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  before_script:
    - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
    - rustup component add rustfmt-preview --toolchain=nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo fmt --all --verbose -- --check
    - cargo clippy --workspace --verbose -- -D warnings

# TODO: Test on Redox with a VM
